### ISSUE TITLE
申请加入

### ISSUE THREAD

**Issue by hjuinj** [Software-Eng-THU-2015/Arrange#1]
github ID: hjuinj
XuetangX account: shuzhe.wang1108@gmail.com

**Comment by anyingbinglong** [comment]
github ID : anyingbinglong
学堂在线：1327979032@qq.com

**Comment by anyingbinglong** [comment]
github ID : anyingbinglong
学堂在线：1327979032@qq.com

**Comment by peterandluc** [comment]
github ID:peterandluc
xuetangX : 597624085@qq.com
