### ISSUE TITLE
申请加入

### ISSUE THREAD

**Issue by norrix** [Software-Eng-THU-2015/Arrange#100]
Github ID: norrix
Xuetang ID: Norris183891

**Comment by cgcgbcbc** [comment]
已邀请，请访问 https://github.com/Software-Eng-THU-2015 接受邀请

**Comment by cgcgbcbc** [comment]
added, 想加入的同学在 https://github.com/orgs/Software-Eng-THU-2015/teams/lanxiangelectricianteam 申请加入
