### ISSUE TITLE
创建团队

### ISSUE THREAD

**Issue by norrix** [Software-Eng-THU-2015/Arrange#101]
团队名称：蓝翔电工班（LanxiangElectricianTeam）
招募人数：1
招募口号：蓝翔电焊工也想学编程，涨姿势。
组长：norrix

**Comment by cgcgbcbc** [comment]
added, 想加入的同学在 https://github.com/orgs/Software-Eng-THU-2015/teams/lanxiangelectricianteam 申请加入
