### ISSUE TITLE
申请加入github组织

### ISSUE THREAD

**Issue by cxsmarkchan** [Software-Eng-THU-2015/Arrange#103]
github账号：cxsmarkchan
学堂在线账号：cxsmarkchan@163.com
学堂在线昵称： Xiaoshuang
Thanks!

**Comment by cgcgbcbc** [comment]
已发送邀请，请访问 https://github.com/Software-Eng-THU-2015 接受邀请

**Comment by cgcgbcbc** [comment]
in team LanxiangElectricianTeam
