### ISSUE TITLE
申请团队

### ISSUE THREAD

**Issue by voidspiral** [Software-Eng-THU-2015/Arrange#104]
github id : chunInsane
team name : Room 114   
team name:  搞个大新闻

**Comment by cgcgbcbc** [comment]
added, https://github.com/orgs/Software-Eng-THU-2015/teams/room-114

**Comment by cgcgbcbc** [comment]
@voidspiral 招募人数？以及请尽快处理加入你们team的申请

**Comment by voidspiral** [comment]
总共三人，已满
