### ISSUE TITLE
加入组织

### ISSUE THREAD

**Issue by haocizhang** [Software-Eng-THU-2015/Arrange#112]
haocizhang 张浩慈 2013013285 学堂id：hihihi

**Comment by cgcgbcbc** [comment]
你不是已经加进来了么？

**Comment by haocizhang** [comment]
是的 没事了 谢谢

Sent from Outlook




On Thu, Oct 29, 2015 at 5:50 AM -0700, "Guang Chen" <notifications@github.com> wrote:












你不是已经加进来了么？
