### ISSUE TITLE
创建新组

### ISSUE THREAD

**Issue by nero19960329** [Software-Eng-THU-2015/Arrange#35]
小组名称：没名儿小组（English name: nameless group）
招募人数：4（算上组长）
招募口号：我们线下组好队了，闲人勿扰
组长Github ID：nero19960329

**Comment by Xuanwo** [comment]
已经添加了，现在你可以添加别的成员到[nameless group](https://github.com/orgs/Software-Eng-THU-2015/teams/nameless-group)中

**Comment by Xuanwo** [comment]
请加入小组的成员在此issue下回复或开启新的issue，方便我进行更新操作~

**Comment by RP011** [comment]
我是本组成员

**Comment by zhoulw13** [comment]
+1
