### ISSUE TITLE
新建团队

### ISSUE THREAD

**Issue by sycmio** [Software-Eng-THU-2015/Arrange#40]
团队名称：中文：AD钙奶 英文：AD calcium milk
招募人数：4（不含组长，加上组长总共5人）
招募口号：懂的加
组长GitHubID：sycmio

**Comment by blackerXHunter** [comment]
【项目实践】 


软件工程是一项解决问题的工程活动，课程在讲授基础知识的同时，将提供一些来源于实际企业的项目选题（待发布），学生可以自愿组队参与项目开发。 

- 项目选择：学生根据题目的简要说明或问题描述，选定一个项目进行开发。对于问题描述的理解，应该与助教或企业代表进行充分交流。 

- 团队组建：要求以团队**（不超过4人）**的方式开发所选题目的软件产品，学生自愿组建团队，选择成员应该综合考虑所在地域距离、技术能力、投入时间、工作态度、配合程度等因素。 



- 开发管理：采用组长负责下的民主式管理方式，确定团队工作规则；讨论制定并执行开发计划，建议采用团队协作开发工具分配任务，跟踪开发进度。 


- 交付要求：开发团队应该按照软件工程方法进行实验项目的开发，交付制品应考虑设计和编码的质量要求，最终交付一个完整可用的系统。 


- 实验检查：项目过程实行严格的里程碑控制（可能会有细微调整），助教或企业代表将对照项目的里程碑对项目制品（包括代码和文档等）进行检查和验收。 


- 项目加分：学生团队在课程结束前交付项目成果，由企业代表进行测试验收，验收合格的团队成员将获得最高20分的加分奖励。 


加粗部分。

**Comment by sycmio** [comment]
管理员您好：我们软工小组就是有5个人的，也跟刘强老师商量过并且获得同意了。我们总不能现在踢出去一个人吧。。。

**Comment by blackerXHunter** [comment]
哦，抱歉，我以为你没看仔细规则。。。没啥事了。。

**Comment by sycmio** [comment]
没事没事。多问一句，您头像是喵森么？（看不懂的话无视我就好）

**Comment by blackerXHunter** [comment]
甜甜圈赛高

**Comment by sycmio** [comment]
啊居然有同好（躺
shirobako简直神赞，中间感动我好多次啊...尤其红毛终于找到工作之后在录音室喊的那句话www

**Comment by blackerXHunter** [comment]
对啊，直接和喵森一起哭的稀里哗T_T。。。两年没哭过的我啊。。。"好像离梦想又进了一步"

**Comment by sycmio** [comment]
您是咱们院的么？方便的话能不能加个qq好友啥的www

**Comment by blackerXHunter** [comment]
不是，只是一名兴趣使然的。。。qq账号好久没上了- -，等我上电脑发给你。话说你人员满了，我把这个issue关了可以么？

**Comment by sycmio** [comment]
可以啊，不过是不是现在我这个团队还没建立啊？因为我在外面并找不到...

**Comment by blackerXHunter** [comment]
ok，帮你加了

**Comment by sycmio** [comment]
您现在在用电脑么？方便的时候加我q吧：915990678

**Comment by blackerXHunter** [comment]
好的，我现在在外面，不记得账号密码，可能要明天网上了。。。额，你有whatsapp或者skype吗？

**Comment by Xuanwo** [comment]
仰慕上面聊得那么high。。

**Comment by blackerXHunter** [comment]
没，话说你发现现在的团队名字一个比一个奇葩么→_→

**Comment by Xuanwo** [comment]
没事，他们组员开心就好。。
