### ISSUE TITLE
申请加入后未收到邀请

### ISSUE THREAD

**Issue by zjcAlistar** [Software-Eng-THU-2015/Arrange#48]
我的github id是zjcAlistar
学堂在线邮箱账户是zhujunchao3311@gmail.com
我已被列入未分组名单但并未在学堂在线讨论区提供的链接页面找到view invitation
点击已有的组名跳转到404
是否能再邀请一次

**Comment by blackerXHunter** [comment]
ok

**Comment by blackerXHunter** [comment]
已经邀请了
