### ISSUE TITLE
I want to create a team~

### ISSUE THREAD

**Issue by chendaxixi** [Software-Eng-THU-2015/Arrange#51]
团队名称：新中韩无敌了(中)  Incredible NCK(英)
招募人数：5
招募口号：都无敌了就问你加不加
组长Github ID: chendaxixi

**Comment by blackerXHunter** [comment]
额。。你们这个团队是一共六个人吗？

**Comment by tmacjx** [comment]
你好，请问如何申请？

**Comment by Xuanwo** [comment]
@tmacjx https://github.com/orgs/Software-Eng-THU-2015/teams/incredible-nck

上述链接中申请即可

**Comment by tmacjx** [comment]
我打开 显示404

**Comment by cgcgbcbc** [comment]
@tmacjx 请先打开 https://github.com/Software-Eng-THU-2015 接受邀请。现在github的组织邀请不会有通知了

**Comment by tmacjx** [comment]
@cgcgbcbc  谢谢 已经解决

**Comment by tmacjx** [comment]
@Xuanwo  亲，已经申请

**Comment by Xuanwo** [comment]
@tmacjx 额，请@这个小组的组长，我并不是这个小组的负责人

**Comment by Xuanwo** [comment]
@cgcgbcbc 哎，现在github加入组织没有邮件提醒了么？

**Comment by cgcgbcbc** [comment]
@Xuanwo 应该是没有邮件提醒了，不知道是否有设置。

**Comment by cgcgbcbc** [comment]
@chendaxixi 请尽快处理你的team的成员申请 https://github.com/orgs/Software-Eng-THU-2015/teams/incredible-nck

**Comment by GengShen** [comment]
申请加入，请审批。

**Comment by cgcgbcbc** [comment]
@chendaxixi 你们team满了麻烦将其他申请加入的请求deny掉。
