### ISSUE TITLE
组织标题讨论

### ISSUE THREAD

**Issue by Xuanwo** [Software-Eng-THU-2015/Arrange#7]
如你们所见，我暂时将组织的标题设置为当前式样。

你们还有更好地想法么？欢迎一起来讨论下~

**Comment by blackerXHunter** [comment]
变个素描或黑白的吧。更加Art一点。

**Comment by Xuanwo** [comment]
Sad，并没有美术功底= =

**Comment by blackerXHunter** [comment]
用个软件转一下不就行了＝ ＝

**Comment by Xuanwo** [comment]
原图没啥意思啊。。

**Comment by blackerXHunter** [comment]
用巴比伦塔吧，具体原因见《人月神话》第七章：巴比伦塔为什么会失败？
![巴比伦塔](http://ww3.sinaimg.cn/large/0060lm7Tgw1ewj7rusgvzj30zk0q1wpv.jpg)

**Comment by Xuanwo** [comment]
Good idea
