### ISSUE TITLE
'叨位去' (150901370477)

### ISSUE THREAD

**Issue by gnoweb** [Software-Eng-THU-2015/Arrange#80]
GithubID：gnoweb
学堂在线账号：'叨位去' (150901370477)
http://www.xuetangx.com/courses/TsinghuaX/34100325X/2015_T1/discussion/forum/users/1370477

**Comment by cgcgbcbc** [comment]
邀请已发送，请访问https://github.com/Software-Eng-THU-2015 接收邀请

**Comment by gnoweb** [comment]
收到，已加入，谢谢。
