### ISSUE TITLE
申请加入

### ISSUE THREAD

**Issue by wmc54321** [Software-Eng-THU-2015/Arrange#81]
学堂在线账号：wmc54321, minchenwang54321@gmail.com
github账号：wmc54321, https://github.com/wmc54321

**Comment by cgcgbcbc** [comment]
邀请已发送，请访问 https://github.com/Software-Eng-THU-2015 接受邀请

**Comment by cgcgbcbc** [comment]
in team [array](https://github.com/orgs/Software-Eng-THU-2015/teams/array)
