### ISSUE TITLE
申请加入

### ISSUE THREAD

**Issue by wqythu13** [Software-Eng-THU-2015/Arrange#83]
github账号：wqythu13    wangqinyu303@gmail.com
学堂在线账号：wqy13   771456505@qq.com

**Comment by cgcgbcbc** [comment]
已邀请，请访问 https://github.com/Software-Eng-THU-2015 接受邀请

**Comment by cgcgbcbc** [comment]
in team [array](https://github.com/orgs/Software-Eng-THU-2015/teams/array)
