### ISSUE TITLE
创建团队

### ISSUE THREAD

**Issue by WyxJsdf** [Software-Eng-THU-2015/Arrange#87]
团队名称（中英文均必须）：琅琊榜 langyabang
招募人数：4(不算组长）
招募口号：然而我并没有看过琅琊榜。。
组长Github ID：WyxJsdf

**Comment by cgcgbcbc** [comment]
邀请已发送，请访问 https://github.com/Software-Eng-THU-2015 接受邀请

**Comment by cgcgbcbc** [comment]
added, https://github.com/orgs/Software-Eng-THU-2015/teams/langyabang
