### ISSUE TITLE
申请创建组织

### ISSUE THREAD

**Issue by namespaceXP** [Software-Eng-THU-2015/Arrange#94]
团队名称（中英文均必须）：环太平洋；Pacific Rim
招募人数：3
招募口号：太平洋手环保太平
组长Github ID：namespaceXP

**Comment by blackerXHunter** [comment]
请问你们的团队一共要五个人（包括组长）吗？

**Comment by namespaceXP** [comment]
抱歉错了=。=  一共四个人

**Comment by blackerXHunter** [comment]
没事，那你们人员已经满了，我把这个issue关了可以吧。
