### ISSUE TITLE
请求加入组织

### ISSUE THREAD

**Issue by phoenixhanren** [Software-Eng-THU-2015/Arrange#97]
ID phoenixhanren
学堂在线：PhoenixFool' (140800250094)

**Comment by cgcgbcbc** [comment]
已邀请，请访问 https://github.com/Software-Eng-THU-2015 接受邀请

**Comment by phoenixhanren** [comment]
请问如何加入未分配人员的名单

**Comment by cgcgbcbc** [comment]
@phoenixhanren 加进了

**Comment by phoenixhanren** [comment]
谢谢
