### ISSUE TITLE
申请加入

### ISSUE THREAD

**Issue by smallAunt** [Software-Eng-THU-2015/Arrange#99]
ID:smallAunt
学堂在线：‘小姨妈’（150901365846）
并且请问如何加入未分配人员的名单
谢谢

**Comment by cgcgbcbc** [comment]
已邀请，请访问 https://github.com/Software-Eng-THU-2015 接受邀请。
当你接受邀请后，可以到本issue下回复，管理员会将你加入未分配人员名单。

**Comment by smallAunt** [comment]
已加入，谢谢
